### ISSUE TITLE
Support for Wear v1

### ISSUE THREAD

**Issue by hoasis2** [20centaurifux/mpcw#2]
Is there any hope to make this very useful app available for WearOS 1.0 (Target API Level 23, Android 6.0) smartwatches as well?

**Comment by 20centaurifux** [comment]
I don't think this app would work under Wear OS 1.

There were major changes between Wear OS 1 and 2 regarding network access. As far as I know Android Wear OS 1 devices need a permanent connection to a phone.

When a watch has a Bluetooth connection to a phone the network is proxied (https://developer.android.com/training/wearables/data-layer/network-access). It's not possible to access local network services, like MPD, in this mode. Therefore MPC Wear connects directly to a Wi-Fi network.

I implemented it this way because MPC Wear should be a standalone app. There are already great MPD clients for phone (MPDroid is awesome, for example).

**Comment by 20centaurifux** [comment]
I just found this document: https://developer.android.com/training/wearables/apps/standalone-apps

Unfortunately the minimum target level for standalone apps is 25.

**Comment by hoasis2** [comment]
Such a pity! Thanks for the reply.
